### PR TITLE
Fill TokenResponse.scope from the Auth callback

### PR DESCRIPTION
**Pull request by hcrohland**
this is a solution to the first option in issue #2

### CODE REVIEW

**Comment by hcrohland** [comment]
Token exchanges can return scope parameters, too according to https://tools.ietf.org/html/rfc6749#section-3.3
And they should take precedence.

Also variant 2 in issue #2 does not make sense.

This fixes issue #2

**Comment by jebrosen** [comment]
I've included a preview of most of these changes in the `early-scope` branch, if you would please test it:

```toml
rocket_oauth2 = { git = "https://github.com/jebrosen/rocket_oauth2/", branch = "early-scope" }
```

The `Debug` change will be included later in a more comprehensive commit.

**Comment by hcrohland** [comment]
Yeah, works for me now. Thanks

And yes, I did not figure out on the fly how to remove the DEBUG commit from the pull request. 
I still think it makes sense to derive DEBUG in general. Especially for learning about the flow.

**Comment by jebrosen** [comment]
Squash merged in 6602377. Thanks for submitting this!

**Pull request closed without merging**
